import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { Feed } from "~/components/Feed";
import { CreatePostWizard } from "~/components/CreatePostWizard";

dayjs.extend(relativeTime);

const Home: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn } = useUser();
  
  //Start fetching asap.
  api.posts.getAll.useQuery();

  // Return empty div if user is not loaded yet.
  if(!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Birber</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-4xl border-x h-full border-slate-400">
          <div className="border-b border-slate-400 p-4 flex">
            { !isSignedIn && (
              <div className="flex justify-center"> 
                <SignInButton/> 
              </div>
            )}
            { isSignedIn && <CreatePostWizard/> }
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
